# Generated by Django 5.2.1 on 2025-05-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrolstation',
            name='busy_level',
            field=models.CharField(default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='petrolstation',
            name='has_atm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petrolstation',
            name='has_coffee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petrolstation',
            name='has_ev_charging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petrolstation',
            name='has_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petrolstation',
            name='wait_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
