# Generated by Django 5.2.1 on 2025-05-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_petrolstation_busy_level_petrolstation_has_atm_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fuelprice',
            name='api_fuelpri_station_ced801_idx',
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='confidence_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='price_change',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='source',
            field=models.CharField(choices=[('user_report', 'User Report'), ('google_places', 'Google Places'), ('gasbuddy', 'GasBuddy'), ('aaa', 'AAA'), ('eia', 'Energy Information Administration'), ('api_scrape', 'API/Web Scraping')], default='user_report', max_length=50),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='verification_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='petrolstation',
            name='data_quality_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='petrolstation',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='petrolstation',
            name='google_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petrolstation',
            name='google_user_ratings_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petrolstation',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petrolstation',
            name='last_google_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petrolstation',
            name='last_price_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petrolstation',
            name='price_update_frequency',
            field=models.CharField(choices=[('high', 'High (Multiple times per day)'), ('medium', 'Medium (Daily)'), ('low', 'Low (Weekly or less)')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='petrolstation',
            name='verification_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(fields=['station', 'fuel_type', '-reported_at'], name='api_fuelpri_station_623e02_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(fields=['source', '-reported_at'], name='api_fuelpri_source_9788bb_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(fields=['confidence_score'], name='api_fuelpri_confide_ae7651_idx'),
        ),
        migrations.AddIndex(
            model_name='petrolstation',
            index=models.Index(fields=['google_place_id'], name='api_petrols_google__94f752_idx'),
        ),
        migrations.AddIndex(
            model_name='petrolstation',
            index=models.Index(fields=['last_google_sync'], name='api_petrols_last_go_9e78eb_idx'),
        ),
        migrations.AddIndex(
            model_name='petrolstation',
            index=models.Index(fields=['data_quality_score'], name='api_petrols_data_qu_047946_idx'),
        ),
    ]
